### ISSUE TITLE
obsolete version warning is too loud

### ISSUE THREAD

**Issue by wlipa** [airbrake/airbrake-ruby#122]
It's annoying to get a yellow alert banner from production exceptions for airbrake-ruby gem versions that are only slightly out of date.

In this case, airbrake-ruby has been out for 4 days and I'm already getting emails yelling about it.  Production servers aren't necessarily updated with new gem libraries every few days, and it's not reasonable to expect that unless there are serious security errors.  Is that the case here?

![screen shot 2016-09-13 at 1 13 15 pm](https://cloud.githubusercontent.com/assets/15970/18489770/dc952be8-79b3-11e6-908a-0ee514d3cde1.png)

**Comment by kyrylo** [comment]
I agree it's not ideal. Currently, we don't have a better way to notify you about new versions. To reduce the noise we only notify you about MINOR versions (1.x.0). I try to maintain a very user-friendly changelog, so feel free to read the changes (no security fixes in the recent version, though). The public API was slightly updated, hence I bumped the MINOR version. That's why you see this message.

I do understand your frustration, so we'll do something about it eventually, so it'll be less annoying. I created an internal ticket about this issue.
