### ISSUE TITLE
blacklist_keys does not remove sensitive information from post bodies

### ISSUE THREAD

**Issue by olbrich** [airbrake/airbrake-ruby#158]
When configuring the `blacklist_keys` setting to include things like `password`, these keys are successfully redacted in parameters that are passed along, however, this information remains in the original post body that may be passed along.  Given that the point of this is to sanitize sensitive information, this information should be removed from there too.  

The original URL needs to be sanitized as well.

**Comment by kyrylo** [comment]
Thanks for the report. I am aware of this mishap and working on a fix. Expect a new release of the library this week.

**Comment by kyrylo** [comment]
Please accept my sincere apologies for the mistake. To provide some context, this is what essentially happened here 😊 

![](http://pngif.com/i/7/e/7eKzmepG9WucihJASweHGD.gif)

This bug was present ever since we released v5. It's pure luck that nobody has had this issue with their custom filters. [The fix](https://github.com/airbrake/airbrake-ruby/issues/159) will be reviewed and merged tomorrow. That's when I'll release v1.7.1, too.

**Comment by kyrylo** [comment]
v1.7.1 is released, so it should be safe to upgrade to it.
