### ISSUE TITLE
blacklist_keys does not remove sensitive information from put bodies

### ISSUE THREAD

**Issue by samneely** [airbrake/airbrake-ruby#186]
* airbrake version: `6.0.0`
* airbrake-ruby version: `2.0.0`
* Ruby version: `2.3.3`
* Framework: Rails => `4.2.7.1`

#### Description

When configuring the `blacklist_keys` setting to include things like password, these keys are successfully redacted in parameters that are passed along, however, this information remains in the original PUT body that may be passed along.

I am using a regular expression to remove passwords like this `/password/`. The password attributes on parameterized objects are still getting included in the PUT bodies like so: `user%5Bpassword%5D=Random12345&user%5Bpassword_confirmation%5D=Random12345`

This issue is similar to the issue reported [here](https://github.com/airbrake/airbrake-ruby/issues/158).

**Comment by kyrylo** [comment]
Thanks for the report! I'll look into it soon.

**Comment by samneely** [comment]
@kyrylo Any updates on this issue?

**Comment by kyrylo** [comment]
Hi, big sorry for the delay! I tried to reproduce this with a new Rails 5.0.2 app but couldn't.

This is what I did:
```
rails new ab
# Then added airbrake to Gemfile
rails g airbrake ID KEY
rails g scaffold thing password:text
# Then added `1/0` to `update` in `things_controller.rb`
rails s
```

```
curl -X PUT -d password=wowowo localhost:3001/things
```

Then I checked the error in the Airbrake dashboard (Occurrences/Parameters). I can see `password` being filtered there.

---

Could you post some steps to reproduce?

**Comment by samneely** [comment]
@kyrylo We are using Rails 4.2.7.1, and it looks like we are experiencing this problem because we are including the `Airbrake::Rack::RequestBodyFilter`. This problem occurs for us when a user attempts to sign into our application with an invalid authenticity token because our sessions expire in memcached every week.

Passwords are being filtered out of the parameters as you described and we expect, but the passwords are not being filtered out of the request bodies that are reported in the Environment tab on Errbit.

**Comment by kyrylo** [comment]
Thanks for the clarification! Now I see what you are talking about. 

`Airbrake::Rack::RequestBodyFilter` reads any request bodies. In order to filter the data inside it, we have to parse it first. The problem is that we can't know the format of the body. Even if the format is known, the body might not be full (because we read only first 4096 bytes of it by default), so parsing it is impossible without clever algorithms.

What you could do is to write a custom filter to ignore bodies in PUT requests (or parse and filter them on your own if you know for sure the format of the body):

```rb
Airbrake.add_filter do |notice|
  if notice.stash[:rack_request]&.put?
    notice[:environment][:body] = nil
  end
end
```

I'm afraid, I can't suggest anything better than this. You can also disable `RequestBodyFilter` altogether.
