### ISSUE TITLE
Propose new config option "additional_endpoint_params"

### ISSUE THREAD

**Issue by aiomaster** [airbrake/airbrake-ruby#294]
Hi,
after this commit https://github.com/airbrake/airbrake-ruby/commit/5d258a28993ca2b2649e02abd93dfa944f207063 there is a problem for redmine_airbrake gem, which provides an airbrake interface to redmine (see https://github.com/jkraemer/redmine_airbrake/issues/2)

The `redmine_airbrake` plugin needs some extra information send with the notification and in the past the `project_key` was abused for that.
I want to suggest another way of dealing with this extra information, but a change to `airbrake-ruby` is necessary.

What if we add just a new optional config option named `additional_endpoint_params` that could take a hash. The hash could be just converted to a query string and added to the endpoint-uri here: https://github.com/airbrake/airbrake-ruby/blob/25eac8e2879cec584801a2531128fb27473cd675/lib/airbrake-ruby/config.rb#L122
If it is not set, nothing changes.

What do you think of this idea, @kyrylo?

**Comment by kyrylo** [comment]
Hi & thanks for your proposal. I have doubts that we want to introduce a new config option for something like this. I'm not sure why you were using `project_key` for something other than `project_key`, but if you want to set it, simply set `config.project_key = 'foobar'`. I have to admit, I don't fully understand what exactly you were doing, but I definitely don't recommend relying on our private APIs because I don't maintain backwards compatibility for them.

P.S. Usually, we attach extra information through filters.

**Comment by aiomaster** [comment]
Thanks @kyrylo,
the hint with the filters to add stuff to the notice payload could be helpfull for me!
