### ISSUE TITLE
Possible to set context for possible error?

### ISSUE THREAD

**Issue by plainlystated** [airbrake/airbrake-ruby#314]
Is there a way to set some context that will be sent along by any downstream error notification?

Something like:
```
Airbrake.context(user_id: @user.id) do
  Foo.bar(@user)
end
```

The goal being that if anything within Foo.bar generates an Airbrake, the context of the user id will be included.  I don't see a way to do this with the current API, but perhaps I'm missing something.

**Comment by kyrylo** [comment]
Is this the same what you ask? https://github.com/airbrake/airbrake/issues/696#issuecomment-366857391

Feel free to chime in and share your thoughts.

**Comment by kyrylo** [comment]
In short, we provide this feature although the API for it is not well-defined.

**Comment by kyrylo** [comment]
Hmm, looks like you are right. It should work in [v2.6.2](https://github.com/airbrake/airbrake-ruby/blob/master/CHANGELOG.md#v262-december-4-2017) by default. However, we stopped gathering thread information by default since [v2.7.0](https://github.com/airbrake/airbrake-ruby/blob/master/CHANGELOG.md#v270-december-13-2017). For modern versions you need to include the Thread filter: https://github.com/airbrake/airbrake-ruby#optional-filters

Please, could you try that and let me know if it works?

**Comment by kyrylo** [comment]
Gentle ping. If this indeed works for you, we might want to add it to the documentation.

**Comment by kyrylo** [comment]
Since v2.9.0 you can set context with `Airbrake.merge_context`: https://github.com/airbrake/airbrake-ruby#airbrakemerge_context
