### ISSUE TITLE
default notifier for multiple applications

### ISSUE THREAD

**Issue by robuye** [airbrake/airbrake-ruby#44]
Hey guys,

I have 2 applications mounted in `config.ru`:

```
map '/a' do
  run ApplicationA::Application
end

map  '/b' do
  run ApplicationB::Application
end
```

`ApplicationA` is normal rails application, `ApplicationB` is a Rails engine. Both applications have Airbrake configured. It's necessary in my setup because I have separate servers running only `ApplicationA` and only `ApplicationB` too.

Configuring Airbrake standard way results in `the 'default' notifier was already configured`.
Configuring dedicated notifiers (`:application_a` and `:application_b`) results in `the 'default' notifier isn't configured`.

I understand where is this coming from, I wonder if there is a clean solution for this sort of setups. I'm fine with both applications sharing the same global config.

Thanks,

Rob

**Comment by kyrylo** [comment]
Hey! Normally Rails engines are handled inside `config/routes.rb`. Are you defining that inside `config.ru` because your engine runs on a separate server? Just want to double check because that looks unconventional to me and I am not sure how you can run that on separate servers given that you define both apps in the same file. A small explanation is appreciated.

There's currently no graceful solution to configure multiple notifiers for the same integration, so you have to use the default one. That said, you can:

1. Configure the notifier only for `ApplicationA::Application` (theoretically it should just work) and `ApplicationB::Application` will simply be reusing it because our integration is a simple Rack middleware, so I assume your engine shares the same middleware stack (IIRC Rails engines itself are middlewares).
2. OR configure Airbrake in `config.ru` instead of the initializer. Simply move the code from there. Make sure that the environment is loaded so you can use `Rails.env`, `Rails.root`, etc.

**Comment by robuye** [comment]
Thanks for the answer.

I have both applications mounted in `config.ru` on `Server1` and only one application mounted on `Server2`.

Server 1:
```
# config.ru
map '/a' do
  run ApplicationA::Application
end

map  '/b' do
  run ApplicationB::Application
end
```

Server 2:
```
# config.ru
map '/' do
  run ApplicationB::Application
end
```

I can't use `config/routes.rb`. There is some additional logic in place that has to happen before a request is dispatched to the right application stack. I think it's not relevant to the issue and I'd prefer not to go into implementation details here.

It's also not mutually exclusive to Rails Engines, the problem applies to any Rack application (grape, sinatra, etc.).

I appreciate the suggestions.

1) Given I configure `ApplicationA`, Airbrake won't work on `server 2`. Skipping the configuration in any application is not a viable option.
2)  Yeah, that should do the trick.

Do you think there is a chance that v5 will allow overriding the config? I'm not in rush to upgrade and I prefer to wait if that's an option.

**Comment by kyrylo** [comment]
I would be very grateful if you could create a test repository modelling your situation. I've been thinking of the best way to resolve this issue, but I do miss a dummy app to verify it my ideas work or not.

**Comment by robuye** [comment]
Will do, just give me few days. I will try to get back to you early next week.

Thanks for taking the time to address this issue.

**Comment by kyrylo** [comment]
Thanks a lot!

**Comment by kyrylo** [comment]
A gentle ping.

**Comment by robuye** [comment]
Apologies for the delay @kyrylo 

I've created a trivial application here: https://github.com/robuye/airbrake-test

To reproduce just clone the repo, `bundle install` and run: `bundle exec rackup server3.ru`.

There are 3 separate rackup files imitating various configurations, 3rd one is crashing.

Airbrake keys are hardcoded and different here, but this doesn't change anything. Setup I'm working on uses ENVs for the keys so both `app1` and `app2` on _server3_ will use the same project_id and key, different ones on _server1_ and _server2_.

Thanks for looking into it, much appreciated!

**Comment by robuye** [comment]
To make this kind of setup look reasonable:

`Styles` - Rails engine, included in multiple applications to share assets and some shared logic. It also runs on it's own dedicated server and provides _Styleguide_ pages with documentation and statistics. We have separate airbrake project assigned to errors coming from here.

`Application` - core application, uses (has it in Gemfile, it's not mounted) `Styles` engine shared logic and assets. It has it's own airbrake project.

I have baby grape application mounted in similar way too, it currently uses parent airbrake settings, but at some point I want to move it to dedicated server (hence have airbrake configured upfront).

**Comment by kyrylo** [comment]
Massive thanks for the demo application! :hand: 

The most difficult conundrum here is deciding what error belongs to what application. For example, let's configure both apps to use different notifiers:

```ruby
# app1.rb
Airbrake.configure(App1) do |c|
  c.project_id = 1111
  c.project_key = '111'
end

# app2.rb
Airbrake.configure(App2) do |c|
  c.project_id = 2222
  c.project_key = '222'
end
```

Let's `use Airbrake::Rack::Middleware` in `server3.ru`. It looks very elegant, but the real question is how should we implement our middleware to support this? The current implementation assumes that you configured your app without specifying an argument (`App1` or `App2`, hence 'default').

If Rack could tell us what app is currently executing the request, then [we would be able to write](https://github.com/airbrake/airbrake/blob/4df0447b18145a6a44d6a56b43e1dae9e233f30a/lib/airbrake/rack/middleware.rb#L41) `Airbrake.notify(notice, params, @app.app_name)`, where `@app.app_name` could be `App1` or `App2`.

But we can't do that, because Rack works differently. Currently, I am thinking that we should provide some kind of API to be able to create multiple Rack middlewares (1 per app, engine, etc). For example:

```ruby
# server3.ru
require_relative './app1'
require_relative './app2'

map '/app1' do
  use Airbrake::Rack::Middleware.for(App1)
  run App1
end

map '/app2' do
  use Airbrake::Rack::Middleware.for(App2)
  run App2
end
```

What do you think?

**Comment by robuye** [comment]
I like it, it looks clean and simple. My only concern is that it will break `server1.ru` setup as we don't have default notifier configured there (or middleware setup). So technically this requires additional changes in multiple places (not a big ones, but still).

It makes me think if we can come up with something that fits the architecture, implies minimum changes and goes beyond simple use case.

Let's add `app3.rb` to the stack and assume we control only `app1.rb`:

```
#app1.rb
Airbrake.configure(App1) do |c|
  #...
end

#app2.rb
Airbrake.configure do |c|
  #...
end

#app3.rb
Airbrake.configure do |c|
  #...
end
```

We can setup custom Middleware for each application, but it won't solve a problem of `App2` and `App3` trying to configure default notifier and it will crash as soon as we call `require`. We won't even have a chance to setup a middleware at this point.

A workaround that comes to my mind would be to provide some sort of wrapper around config, something along these lines:

```
#server3.ru
require `airbrake`

require_relative './app1'

Airbrake.with_defaults(notifier: :app2) do
  require_relative './app2'
end

Airbrake.with_defaults(notifier: :app3) do
  require_relative './app3'
end

map '/app1' do
  use Airbrake::Rack::Middleware.for(:app1)
  run App1
end

map '/app2' do
  use Airbrake::Rack::Middleware.for(:app2)
  run App2
end

map '/app3' do
  use Airbrake::Rack::Middleware.for(:app3)
  run App3
end
```

(I'm not using constants here because config happens before we have a chance to require an app)

We might even leave `App1` with default notifier and skip `use Airbrake::Rack::Middleware.for(:app1)`.

We can force `App3` to use `:app2` notifier by doing:

```
map `/app3' do
  use Airbrake::Rack::Middleware.for(:app2)
  run App3
end
```

I think this wouldn't introduce any breaking changes and gives some extra flexibility while following open/closed principle.

**Comment by kyrylo** [comment]
Hey! I'm having troubles with understanding your workaround. Could you please elaborate what `with_defaults` does? You also said "let's assume we control only `app1.rb`". What real world scenario leads to this situation?

That said, I was able to write some [initial implementation](https://github.com/airbrake/airbrake/pull/515) to support `server3.ru` scenario. I do get an error about "default" notifier when I try to run `bundle exec rackup server2.ru` (or `server1.ru`).

**Comment by kyrylo** [comment]
This feature might go into the [upcoming release](https://github.com/airbrake/airbrake/pull/515) if it gets resolved in time :)

**Comment by robuye** [comment]
@kyrylo apologies for the delay.

I'm currently away, I will give you an in-depth answer with example code when I'm back next week. I'm also more than happy to follow up with a proper p/r if you find it useful.

Thanks so much for taking the time to do the work, it's much appreciated!

**Comment by kyrylo** [comment]
Sure! Thanks for the update, I appreciate your interest. The PR is also welcome, that said please do take a look at mine when you have time :)

**Comment by kyrylo** [comment]
We couldn't figure out best way to implement this and [agreed to close this for now](https://github.com/airbrake/airbrake-ruby/pull/62#issuecomment-206788580).
