### ISSUE TITLE
Increase in CPU usage when performance_stats = true

### ISSUE THREAD

**Issue by lenon** [airbrake/airbrake-ruby#488]
Hi,
Last week we upgraded `airbrake` from 9.2.2 to 9.3.0 and `airbrake-ruby` from `4.4.0` to `4.5.0`. After the deploy of this upgrade, we had an increase in CPU usage and latency times in our app which was fixed by setting `performance_stats` to `false`. Here's our latency metrics:

![Screen_Shot_2019-07-01_at_15_09_28](https://user-images.githubusercontent.com/64386/60458626-7ef8ed80-9c15-11e9-99a5-7ce9c5a14bd4.png)

And CPU usage metrics from one of our VMs:

![Screen_Shot_2019-07-01_at_15_16_42](https://user-images.githubusercontent.com/64386/60459204-de0b3200-9c16-11e9-833f-a8cfa38b1e18.png)

These metrics are from DataDog and are reported by `ddtrace` gem.

We also had `**Airbrake: Your account does not accept APM data` logged hundreds of times per minute. Maybe that's because we need to decrease our log level, but I'm not sure.

Everything looks normal in our app now, but I'm still opening this issue so you folks can check if there are some improvements that can be done to reduce CPU usage. I also think that would be good to mention something about `performance_stats` in `airbrake` changelog.

Additional info:

* Airbrake version: 9.3.0
* Ruby version: 2.6.3
* Framework name & version: Rails 5.2.3, Sidekiq 5.2.7

**Comment by kyrylo** [comment]
Thanks for the useful info. I addressed these performance hits in https://github.com/airbrake/airbrake-ruby/pull/490 and https://github.com/airbrake/airbrake-ruby/pull/491. I don't have 100% confidence that this will resolve all the performance issues that you spotted on the graph but it is a significant improvement.

I also suspect that you may run your app in the debug mode (debug logger severity). If that's the case, try to use `error` severity. It's a lot to ask, so what you could do is configure your airbrake notifier to a custom severity.

In other news (unrelated to this issue but also about logging), check this out: https://github.com/airbrake/airbrake#logging
We now log to `log/airbrake.log` by default (only for new Rails apps), so with that setting it'll be easier to debug Airbrake.

P.S. We do mention the `performance_stats = true` change in this project but it's probably a good idea to duplicate that info in `airbrake` as well, since you're not the first person to be confused.

**Comment by lenon** [comment]
@kyrylo thanks for taking a look at this. We are not running our app in debug mode. I checked our log level and it is the default from Rails, which is "info". It makes me think that the severity of the message we saw in our logs is "info" or "error".

**Comment by kyrylo** [comment]
Hey @lenon. Could you please check out airbrake v9.4.3? It contains a significant performance improvement. I would really appreciate if you could share how it impacts your app.
