### ISSUE TITLE
airbrake issues with lack of detail

### ISSUE THREAD

**Issue by raosev** [airbrake/airbrake-ruby#678]
Good day team!

We're having an odd issue with our Airbrake dashboard and sadly we have not been able to diagnose it :-(.

Here's the thing, issues being reported in our production environment... are showing clearly less details compared to the issues we generate in our local/development environment, making our debugging work much more complicated. Please note, this is not always happening, but it is the majority of the cases.

Here's an example of a production issue:

![error_prod](https://user-images.githubusercontent.com/218480/149834474-b35fdc5d-73ae-46f1-9c18-d94c7853694c.png)

Here's the exact same error,  but raised at my local environment

![params_2](https://user-images.githubusercontent.com/218480/149836840-0553244f-3962-421c-be52-27b8f924740f.png)

![dev_error](https://user-images.githubusercontent.com/218480/149834854-1a5cc029-796a-4f0e-9403-b9eeceafa401.png)

Notice that the `production` example is not showing a `Parameters` block at all, in addition, the `Context` block has less details compared to the example from development.

Please note this is just an example, overall this seems to be happening around 80% of the times within the issues in our dashboard. We were wondering if you had any idea around what could possibly be the problem? :pray: 

This is our current configuration:

```
Airbrake.configure do |config|
    config.app_version = Rails.application.version

    # https://github.com/airbrake/airbrake-ruby#project_id--project_key
    config.project_id  = Rails.application.credentials.airbrake_project_id
    config.project_key = Rails.application.credentials.airbrake_project_key

    config.root_directory = Rails.root

    config.logger = Rails.logger

    config.environment = Rails.env

    config.ignore_environments = %w[test]

    config.blocklist_keys = Rails.application.config.filter_parameters

    config.performance_stats = false # Rails.env.production?
    config.job_stats = false # Rails.env.production?
  end

  Airbrake.add_filter do |notice|
    notice.ignore! if notice.stash[:exception].is_a?(SignalException)
    notice.ignore! if notice.stash[:exception].is_a?(OmniAuth::Strategies::OAuth2::CallbackError)
    notice.ignore! if notice.stash[:exception].is_a?(ActionController::RoutingError)
    notice.ignore! if notice.stash[:exception].is_a?(Net::HTTPServerException)
  end

  Airbrake.add_filter(Airbrake::Rack::RequestBodyFilter.new)
```

This is our stack:

```
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
airbrake (12.0.0)
airbrake-ruby (6.0.1)
pasenger (6.0.10)
rails (6.0.4)
```

**Comment by kyrylo** [comment]
Hey @raosev!

This is probably related to Passenger. How exactly? I am not sure because I don't use it. Let's try to break it down bit by bit. 

Firstly, I noticed the `lastCheckout` key is not available on production for you. When you deploy your app, do you have `.git` directory included? If you don't deploy/keep `.git`, then `lastCheckout` won't be available.

Secondly, the `action` and `component` keys may be missing if the context the error was reported from doesn't contain such information. In your local environment the error is coming from a Rails controller. Is it the same for production?

Next, the `headers` key comes from [here](https://github.com/airbrake/airbrake/blob/dfbd162a6f9f6bdeee7eeb5e7d1449d1770091fb/lib/airbrake/rack/http_headers_filter.rb). The filter that collects them is included [here](https://github.com/airbrake/airbrake/blob/dfbd162a6f9f6bdeee7eeb5e7d1449d1770091fb/lib/airbrake/rack/middleware.rb#L93-L102). In your production environment you can go to the Rails console and execute `Airbrake.notice_notifier.inspect`. This will show what filters your notifier is using. `Airbrake::Rack::HttpHeadersFilter` should be mentioned there.
