### ISSUE TITLE
Set error_host and apm_host to host by default

### ISSUE THREAD

**Issue by vpereira** [airbrake/airbrake-ruby#710]
Hallo @airbake team

Please set the default configuration settings https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/config.rb#L166-L167 to `host` and have maybe `host` pointing to `https://api.airbrake.io`. 

As it is configured  now, people using https://github.com/airbrake/airbrake and setting only `config.host` would send unnecessarily  their performance and (maybe error data?) to `airbrake.io`

**Comment by kyrylo** [comment]
Hey Victor!

`host` is actually not even documented (if it is, please point me to the location so that I can remove it). We have `error_host` and `apm_host`. `host` is still supported because of legacy projects, which would break if we removed it.

If you meant to use `host`, please use `error_host` instead.

**Comment by vpereira** [comment]
Hey @kyrylo,

Thank you for your answer!

Sorry if i wasn't explicit. I'm was actually not sure if it was an issue for this gem or [airbrake](https://github.com/airbrake/airbrake/). 

I think you are right `host` shouldn't be supported or exposed, but that's how people still configuring it everywhere https://cs.github.com/?q=Airbrake.configure%20language%3ARuby&scopeName=All%20repos&scope= .. maybe there are still some documentation on "how to setup airbrake with errbit" pointing to this?  

Either way, I think would be sensible to either add a deprecation warning when using `config.host` and remove the defaults pointing to `https://api.airbrake.io` otherwise i can imagine that many applications are just pushing involuntarily their APM or even backtraces to `airbrake.io` .. or am I missing some condition which would avoid it,  while reading the code?

**Comment by kyrylo** [comment]
> but that's how people still configuring it everywhere

It used to be documented, but at some point I removed the docs for `host` because we introduced `error_host` and `apm_host`. A good portion of the projects that are shown by the GitHub search you linked to are legacy projects. I don't think it's necessary to remove or deprecate `host`. The CHANGELOG clearly mentions that `host` is an alias for `error_host`: https://github.com/airbrake/airbrake-ruby/blob/master/CHANGELOG.md#v500rc1-july-13-2020

Adding a deprecation warning might be sensible, though. That said, `host` won't go anywhere because it'll just annoy a lot of users for no good reason. A deprecation warning is a minor annoyance in comparison.

> maybe there are still some documentation on "how to setup airbrake with errbit" pointing to this?

We don't have such documentation anywhere at Airbrake-owned resources. I am not an Errbit user myself, so I'm not sure.
